threadCount: 4

fromProperties:
  url: jdbc:oracle:thin:@(description=(address=(host=localhost)(protocol=tcp)(port=1521))(connect_data=(service_name=ORCLPDB1)))
  user: t
  password: t
toProperties:
  url: jdbc:postgresql://localhost:5432/postgres
  user: test
  password: test